openapi: 3.0.0
info:
  title: User API
  description: User API
  version: 1.0.0
servers:
  - url: http://localhost:3102/user-service
tags:
  - name: User
    description: APIs of user
paths:
  /register:
    description: Register a user
    post:
      tags:
        - User
      description: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post-user'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: 2
        400:
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response-error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response-error'
  /login:
    description: Login user
    post:
      tags:
        - User
      description: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: abc@gmail.com
                password:
                  type: string
                  example: 123456abc
      responses:
        200:
          description: Login Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        400:
          description: Invalid Credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response-error'
components:
  schemas:
    post-user:
      type: object
      properties:
        email:
          type: string
          example: abc@gmail.com
        password:
          type: string
          example: 123456abc
        firstName:
          type: string
          example: Ricky
        lastName:
          type: string
          example: Karunakaran
    pagination:
      type: object
      properties:
        currentPage:
          type: number
          example: 2
        totalPages:
          type: number
          example: 5

    response-error:
      type: object
      properties:
        message:
          type: string
          example: Server Error. Please try later
